# Generated by Django 2.0.6 on 2018-06-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('OT', 'Other')], max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('GEN', 'General'), ('OBC', 'Other Backward Class'), ('SC', 'Scheduled Caste')], max_length=10)),
                ('blood_group', models.CharField(choices=[('OM', 'O-Minus'), ('OP', 'O-Positive'), ('AM', 'A-Minus'), ('AP', 'A-Positive'), ('BM', 'B-Minus'), ('ABM', 'AB-Minus'), ('ABP', 'AB-Positive'), ('BP', 'B-Positive')], max_length=10)),
                ('type', models.CharField(choices=[('S', 'Student'), ('F', 'Faculty'), ('U', 'User'), ('A', 'Alumni')], max_length=10)),
            ],
        ),
    ]
